name: myapp
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5

  cupertino_icons: ^1.0.2
  http: ^0.13.4  # Add the HTTP package for API requests

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  